apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-demo-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-demo
spec:
  serviceName: pg-demo
  replicas: 1
  selector:
    matchLabels:
      app: pg-demo
  template:
    metadata:
      labels:
        app: pg-demo
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: pg-demo-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          readinessProbe:
            exec: { command: [ "pg_isready","-U","demo" ] }
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: init
          configMap:
            name: pg-demo-init
            items:
              - key: init.sql
                path: init.sql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pg-demo
spec:
  selector:
    app: pg-demo
  ports:
    - port: 5432
      targetPort: 5432